// Generated from the Biome parsers in iLEAPP (https://github.com/abrignoni/iLEAPP,
// MIT, Alexis Brignoni and contributors) by Scripts/extract-biome-schema.py.
// Edit that script and regenerate rather than editing this file.
//
// The wire format carries field numbers, not names. These are the names the
// forensics community has established for each stream by comparing many
// devices against known activity, which is the only way they can be known:
// Apple does not publish the .proto files.

import Foundation

extension BiomeSchema {

    static let table: [Stream] = [
        Stream(name: "AeroML.Insights.PhotosSearchInsights", title: "Photos Search Insights", fields: [
            Field(path: "9", label: "Search Term"),
            Field(path: "22", label: "Language"),
            Field(path: "23", label: "Region"),
            Field(path: "24", label: "Schema Version"),
        ]),
        Stream(name: "App.Activity", title: "App Activity", fields: [
            Field(path: "1", label: "Bundle ID"),
            Field(path: "2", label: "Activity Type"),
            Field(path: "3", label: "App Activity"),
            Field(path: "5", label: "Expiration Timestamp"),
            Field(path: "8", label: "Activity UUID"),
            Field(path: "10", label: "Item URI"),
            Field(path: "14", label: "Payload"),
            Field(path: "15", label: "Session UUID"),
            Field(path: "16", label: "Source"),
        ]),
        Stream(name: "App.InFocus", title: "In Focus", fields: [
            Field(path: "3", label: "Action", values: [0: "Background", 1: "Foreground"]),
            Field(path: "4", label: "Start Time", kind: .appleTime),
            Field(path: "6", label: "Bundle ID"),
        ]),
        Stream(name: "App.Install", title: "App Install", fields: [
            Field(path: "1.1", label: "Activity"),
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "3", label: "Time End", kind: .appleTime),
            Field(path: "4.3", label: "Bundle ID"),
            Field(path: "5", label: "Action GUID", kind: .text),
            Field(path: "7", label: "Bundle Info"),
            Field(path: "8", label: "Time Write", kind: .appleTime),
        ]),
        Stream(name: "App.Installation", title: "App Installation", fields: [
            Field(path: "1", label: "App"),
            Field(path: "2", label: "Event Type"),
            Field(path: "3", label: "Detail"),
            Field(path: "4", label: "Event Timestamp"),
        ]),
        Stream(name: "App.Intent", title: "Intents", fields: [
            Field(path: "1.16", label: "B"),
            Field(path: "2", label: "Typeofintent"),
            Field(path: "3", label: "A"),
            Field(path: "4", label: "Classname"),
            Field(path: "5", label: "Action"),
            Field(path: "5.1.2", label: "A"),
            Field(path: "5.1.4", label: "A"),
            Field(path: "8", label: "Deserialized Plist"),
            Field(path: "15", label: "C"),
        ]),
        Stream(name: "App.Intents.Transcript", title: "App Intents Transcript", fields: [
            Field(path: "1", label: "Bundle ID"),
            Field(path: "4", label: "Intent Timestamp"),
            Field(path: "5", label: "Intent"),
            Field(path: "6", label: "Intent"),
            Field(path: "8", label: "Phrase"),
            Field(path: "8.2", label: "Display"),
            Field(path: "8.2.1", label: "Inner"),
            Field(path: "8.2.1.1", label: "Phrase Template"),
        ]),
        Stream(name: "App.LocationActivity", title: "App Location Activity", fields: [
            Field(path: "1", label: "Bundle ID"),
            Field(path: "2", label: "Activity Type"),
            Field(path: "5", label: "Expiration Timestamp"),
            Field(path: "9", label: "URL"),
            Field(path: "14", label: "Payload"),
            Field(path: "15", label: "Activity UUID"),
            Field(path: "16", label: "Source"),
            Field(path: "19", label: "Donation Type"),
            Field(path: "26", label: "City"),
            Field(path: "29", label: "Street Address"),
            Field(path: "32", label: "Postal Code"),
            Field(path: "34", label: "Title"),
            Field(path: "35", label: "Place URL"),
        ]),
        Stream(name: "App.RelevantShortcuts", title: "App Relevant Shortcuts", fields: [
            Field(path: "1", label: "Bundle ID"),
            Field(path: "3", label: "Plist"),
        ]),
        Stream(name: "App.WebUsage", title: "App Web Usage", fields: [
            Field(path: "1", label: "GUID / UUID", kind: .text),
            Field(path: "2", label: "Timestamp", kind: .real),
            Field(path: "4", label: "Full URL", kind: .text),
            Field(path: "5", label: "Domain / host", kind: .text),
            Field(path: "6", label: "Bundle ID", kind: .text),
        ]),
        Stream(name: "AppleIntelligence.Availability", title: "Apple Intelligence Availability", fields: [
            Field(path: "1", label: "State 1"),
            Field(path: "1.1", label: "State 1"),
            Field(path: "2", label: "State 2"),
            Field(path: "2.1", label: "State 2"),
            Field(path: "3", label: "State 3"),
            Field(path: "6", label: "Language"),
        ]),
        Stream(name: "AppleIntelligence.Reporting.AssetDeliveryLog.Availability", title: "Apple Intelligence Asset Availability", fields: [
            Field(path: "1", label: "Event"),
            Field(path: "2", label: "Result"),
        ]),
        Stream(name: "AppleIntelligence.Reporting.AssetDeliveryLog.ModelCatalog", title: "Apple Intelligence Model Catalog", fields: [
            Field(path: "1", label: "Event"),
            Field(path: "2", label: "Result"),
        ]),
        Stream(name: "AppleIntelligence.Reporting.AssetDeliveryLog.SoftwareUpdateController", title: "Apple Intelligence Software Update", fields: [
            Field(path: "1", label: "Event"),
            Field(path: "2", label: "Result"),
        ]),
        Stream(name: "AppleIntelligence.Reporting.AssetDeliveryLog.UnifiedAssetFramework", title: "Apple Intelligence Unified Asset", fields: [
            Field(path: "1", label: "Event"),
            Field(path: "2", label: "Result"),
        ]),
        Stream(name: "AppleIntelligence.Reporting.SafetyOverrides", title: "Apple Intelligence Safety Overrides", fields: [
            Field(path: "1", label: "Event"),
            Field(path: "2", label: "Result"),
        ]),
        Stream(name: "Audio.Route", title: "Audio Route", fields: [
            Field(path: "2", label: "Route Name"),
            Field(path: "3", label: "Port Type"),
            Field(path: "4", label: "Port Name"),
        ]),
        Stream(name: "Autonaming.Messages.MessageIds", title: "Autonaming Message IDs", fields: [
            Field(path: "2", label: "Bundle ID"),
            Field(path: "3", label: "Chat ID"),
            Field(path: "4", label: "Message GUID"),
            Field(path: "6", label: "Message GUID"),
            Field(path: "7", label: "Chat ID"),
            Field(path: "10", label: "Message Timestamp"),
        ]),
        Stream(name: "Backlight", title: "Backlight", fields: [
            Field(path: "1", label: "Timestamp", kind: .appleTime),
        ]),
        Stream(name: "CameraCapture.AutoFocusROI", title: "Camera Auto Focus ROI", fields: [
            Field(path: "1", label: "Camera Port"),
        ]),
        Stream(name: "CarPlay.Connected", title: "CarPlay Connected", fields: [
            Field(path: "1", label: "CarPlay State", values: [0: "Not Connected", 1: "Connected"]),
        ]),
        Stream(name: "Clock.Alarm", title: "Clock Alarm", fields: [
            Field(path: "3", label: "Alarm ID"),
        ]),
        Stream(name: "CommCenter.Call.EmergencyVoiceCall", title: "Emergency Voice Call", fields: [
            Field(path: "1", label: "Emergency Number"),
            Field(path: "2", label: "Mobile Country Code"),
            Field(path: "3", label: "Mobile Network Code"),
            Field(path: "7", label: "Duration Seconds"),
        ]),
        Stream(name: "Device.BootSession", title: "Boot Session", fields: [
            Field(path: "1", label: "Session ID"),
            Field(path: "2", label: "Session State", values: [0: "Session End", 1: "Session Start"]),
        ]),
        Stream(name: "Device.Display.Backlight", title: "Backlight", fields: [
            Field(path: "1", label: "Timestamp", kind: .appleTime),
        ]),
        Stream(name: "Device.Display.InterfaceOrientation", title: "Interface Orientation", fields: [
            Field(path: "1", label: "Interface Orientation", values: [0: "Unknown", 1: "Portrait", 2: "Portrait Upside Down", 3: "Landscape Right", 4: "Landscape Left"]),
        ]),
        Stream(name: "Device.KeybagLocked", title: "Keybag Locked", fields: [
            Field(path: "1", label: "Keybag Locked", values: [0: "Unlocked", 1: "Locked"]),
        ]),
        Stream(name: "Device.Metadata", title: "Device Metadata", fields: [
            Field(path: "2", label: "OS Build"),
            Field(path: "3", label: "Type"),
            Field(path: "4", label: "OS Build"),
        ]),
        Stream(name: "Device.Networking.EdgeSelection", title: "Networking Edge Selection", fields: [
            Field(path: "1", label: "IP Address", kind: .bytes),
            Field(path: "2", label: "IP Version", kind: .integer),
            Field(path: "3", label: "Prefix Length", kind: .integer),
            Field(path: "4", label: "Interface", kind: .bytes),
            Field(path: "5", label: "Radio Technology", kind: .bytes),
            Field(path: "7", label: "Country", kind: .bytes),
            Field(path: "8", label: "Time Zone", kind: .bytes),
        ]),
        Stream(name: "Device.Power.BatteryLevel", title: "Battery Level", fields: [
            Field(path: "1", label: "Level"),
        ]),
        Stream(name: "Device.Power.LowPowerMode", title: "Low Power Mode", fields: [
            Field(path: "1", label: "Low Power Mode", values: [0: "Off", 1: "On"]),
        ]),
        Stream(name: "Device.Power.PluggedIn", title: "Power Plugged In", fields: [
            Field(path: "1", label: "Power State", values: [0: "Not Plugged In", 1: "Plugged In"]),
        ]),
        Stream(name: "Device.ScreenLocked", title: "Screen Locked", fields: [
            Field(path: "1", label: "Screen Locked", values: [0: "Unlocked", 1: "Locked"]),
        ]),
        Stream(name: "Device.SilentMode", title: "Silent Mode", fields: [
            Field(path: "1", label: "Ringer State", values: [0: "Ringer On", 1: "Silent"]),
            Field(path: "4", label: "Reason"),
        ]),
        Stream(name: "Device.Thermals.BatteryTemperature", title: "Battery Temperature", fields: [
            Field(path: "1", label: "Temperature"),
        ]),
        Stream(name: "Device.TimeZone", title: "Device TimeZone", fields: [
            Field(path: "2", label: "Timezone", kind: .text),
        ]),
        Stream(name: "Device.Wireless.AirplaneMode", title: "Airplane Mode", fields: [
            Field(path: "1", label: "Airplane Mode", values: [0: "Off", 1: "On"]),
        ]),
        Stream(name: "Device.Wireless.Bluetooth", title: "Bluetooth", fields: [
            Field(path: "1", label: "MAC"),
            Field(path: "2", label: "Name"),
        ]),
        Stream(name: "Device.Wireless.CellularDataEnabled", title: "Cellular Data Enabled", fields: [
            Field(path: "1", label: "Cellular Data Enabled", values: [0: "Disabled", 1: "Enabled"]),
        ]),
        Stream(name: "Discoverability.Signals", title: "Discoverability Signals", fields: [
            Field(path: "1", label: "Signal"),
            Field(path: "2", label: "Discoverability Signals"),
            Field(path: "3", label: "Context Msg"),
            Field(path: "4", label: "Payload"),
        ]),
        Stream(name: "Emoji.Engagement", title: "Emoji Engagement", fields: [
            Field(path: "1", label: "Emoji"),
            Field(path: "3", label: "Sub"),
        ]),
        Stream(name: "FrontBoard.DisplayElement", title: "FrontBoard Display Element", fields: [
            Field(path: "1", label: "Event Timestamp"),
            Field(path: "2", label: "Scene ID"),
            Field(path: "3", label: "Bundle ID"),
            Field(path: "9", label: "Display"),
        ]),
        Stream(name: "Keyboard.TokenFrequency", title: "Keyboard Learned Tokens", fields: [
            Field(path: "1", label: "Token"),
            Field(path: "1.1", label: "Token"),
            Field(path: "3", label: "Frequency"),
        ]),
        Stream(name: "Location.Visit", title: "Location Visit", fields: [
            Field(path: "1", label: "Detection Timestamp"),
            Field(path: "3", label: "Geo"),
            Field(path: "4", label: "Arrival Timestamp"),
            Field(path: "5", label: "Departure Timestamp"),
            Field(path: "6", label: "Confidence"),
            Field(path: "8", label: "Place"),
        ]),
        Stream(name: "MLSE.ShareSheet.ConversationUserInteraction", title: "Share Sheet Conversation", fields: [
            Field(path: "1", label: "Bundle ID"),
            Field(path: "2", label: "Contact Handle"),
            Field(path: "11", label: "Interaction Timestamp"),
        ]),
        Stream(name: "Media.NowPlaying", title: "Now Playing", fields: [
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "5", label: "Artist", kind: .text),
            Field(path: "8", label: "Title", kind: .text),
            Field(path: "10", label: "Media Type", kind: .text),
            Field(path: "15", label: "Bundle ID", kind: .text),
        ]),
        Stream(name: "Media.Route", title: "Media Route", fields: [
            Field(path: "2", label: "Route Name"),
            Field(path: "4", label: "Detail"),
        ]),
        Stream(name: "Messages.Read", title: "Messages Read", fields: [
            Field(path: "1", label: "Message ID"),
        ]),
        Stream(name: "NotesContent", title: "Notes", fields: [
            Field(path: "1", label: "Identifier 1", kind: .text),
            Field(path: "2", label: "Identifier 2", kind: .text),
            Field(path: "3", label: "Timestamp", kind: .appleTime),
            Field(path: "5", label: "Note", kind: .text),
        ]),
        Stream(name: "Notification", title: "Notifications", fields: [
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "5", label: "Data5", kind: .text),
            Field(path: "8", label: "Data1", kind: .text),
            Field(path: "9", label: "Data2", kind: .text),
            Field(path: "12", label: "Data3", kind: .text),
            Field(path: "14", label: "Bundle ID", kind: .text),
            Field(path: "15", label: "Data4"),
        ]),
        Stream(name: "Notification.Usage", title: "Notification Usage", fields: [
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "8", label: "Notification content"),
            Field(path: "12", label: "Notification content 2"),
            Field(path: "14", label: "Application name"),
        ]),
        Stream(name: "NowPlaying", title: "Now Playing", fields: [
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "5", label: "Artist", kind: .text),
            Field(path: "8", label: "Title", kind: .text),
            Field(path: "10", label: "Media Type", kind: .text),
            Field(path: "15", label: "Bundle ID", kind: .text),
        ]),
        Stream(name: "OSAnalytics.Hardware.Reliability", title: "Hardware Reliability", fields: [
            Field(path: "1", label: "Hardware", kind: .text),
        ]),
        Stream(name: "ProactiveHarvesting.Mail", title: "Proactive Harvesting Mail", fields: [
            Field(path: "2", label: "Message ID"),
            Field(path: "3", label: "Message Date"),
            Field(path: "11", label: "Subject"),
        ]),
        Stream(name: "ProactiveHarvesting.Messages", title: "Proactive Harvesting Messages", fields: [
            Field(path: "1", label: "GUID"),
            Field(path: "2", label: "Service and Handle"),
            Field(path: "10", label: "Content"),
            Field(path: "11", label: "Sender"),
        ]),
        Stream(name: "Safari.Navigations", title: "Safari Navigations", fields: [
            Field(path: "1", label: "Host"),
            Field(path: "2", label: "Rounded Timestamp"),
            Field(path: "5", label: "Country"),
            Field(path: "8", label: "URL"),
        ]),
        Stream(name: "Safari.WebPagePerformance", title: "Safari Web Page Performance", fields: [
            Field(path: "1", label: "Detail"),
            Field(path: "2", label: "Rounded Timestamp"),
        ]),
        Stream(name: "ScreenTime.AppUsage", title: "ScreenTime App Usage", fields: [
            Field(path: "1", label: "Event"),
            Field(path: "3", label: "Bundle ID"),
        ]),
        Stream(name: "ShareSheet.Feedback", title: "Share Sheet Feedback", fields: [
            Field(path: "2", label: "Activity Type"),
            Field(path: "3", label: "Session ID"),
            Field(path: "5", label: "Event UUID"),
            Field(path: "11", label: "Offered Candidates"),
            Field(path: "15", label: "Source App"),
            Field(path: "16", label: "Chosen Activity"),
        ]),
        Stream(name: "Siri.Remembers.AssistantSuggestions", title: "Siri Remembers Assistant Suggestions", fields: [
            Field(path: "1", label: "Metadata"),
            Field(path: "1.1", label: "Event ID"),
            Field(path: "1.2", label: "Intent Class"),
            Field(path: "1.4", label: "Bundle ID"),
            Field(path: "1.8", label: "Suggestion Timestamp"),
            Field(path: "1.11", label: "Metadata"),
        ]),
        Stream(name: "Siri.Remembers.AudioHistory", title: "Siri Remembers Audio History", fields: [
            Field(path: "1", label: "Metadata"),
            Field(path: "1.1", label: "Intent UUID"),
            Field(path: "1.2", label: "Intent Class"),
            Field(path: "1.4", label: "Bundle ID"),
            Field(path: "1.8", label: "Playback Timestamp"),
            Field(path: "1.12", label: "Media ID"),
        ]),
        Stream(name: "Siri.Remembers.CallHistory", title: "Siri Remembers Call History", fields: [
            Field(path: "1", label: "Metadata"),
            Field(path: "1.2", label: "Intent Class"),
            Field(path: "1.4", label: "Bundle ID"),
            Field(path: "1.6", label: "Direction"),
            Field(path: "1.8", label: "Call Timestamp"),
            Field(path: "1.11", label: "Group Metadata"),
            Field(path: "1.12", label: "Conversation ID"),
            Field(path: "1.13", label: "Call GUID"),
        ]),
        Stream(name: "Siri.Remembers.InteractionHistory", title: "Siri Remembers Interaction History", fields: [
            Field(path: "1", label: "Metadata"),
            Field(path: "1.1", label: "Intent UUID"),
            Field(path: "1.2", label: "Intent Class"),
            Field(path: "1.3", label: "Domain"),
            Field(path: "1.4", label: "Bundle ID"),
            Field(path: "1.8", label: "Intent Timestamp"),
            Field(path: "1.13", label: "Item GUID"),
        ]),
        Stream(name: "Siri.Remembers.MessageHistory", title: "Siri Remembers Message History", fields: [
            Field(path: "1", label: "Metadata"),
            Field(path: "1.2", label: "Intent Class"),
            Field(path: "1.4", label: "Bundle ID"),
            Field(path: "1.6", label: "Direction"),
            Field(path: "1.8", label: "Message Timestamp"),
            Field(path: "1.11", label: "Group Metadata"),
            Field(path: "1.12", label: "Chat ID"),
            Field(path: "1.13", label: "Message GUID"),
        ]),
        Stream(name: "Siri.UI", title: "Siri UI", fields: [
            Field(path: "2", label: "Session ID"),
            Field(path: "3", label: "Presentation"),
            Field(path: "4", label: "Dismissal Reason"),
            Field(path: "5", label: "Interface State", values: [0: "Dismissed", 1: "Presented"]),
            Field(path: "7", label: "Related ID"),
        ]),
        Stream(name: "SystemSettings.SearchTerms", title: "System Settings Search Terms", fields: [
            Field(path: "1", label: "Search Term"),
            Field(path: "2", label: "Results"),
        ]),
        Stream(name: "Text.InputSession", title: "Text Input Session", fields: [
            Field(path: "1", label: "Duration", kind: .real),
            Field(path: "2", label: "Time Start", kind: .appleTime),
            Field(path: "3", label: "Bundle ID", kind: .text),
        ]),
        Stream(name: "TextInputSession", title: "Text Input Session", fields: [
            Field(path: "1", label: "Duration", kind: .real),
            Field(path: "2", label: "Time Start", kind: .appleTime),
            Field(path: "3", label: "Bundle ID", kind: .text),
        ]),
        Stream(name: "UniversalRecents.UserActivity.Metadata", title: "User Activity Metadata", fields: [
            Field(path: "2", label: "Activity type"),
            Field(path: "4", label: "Description"),
            Field(path: "5", label: "Bundle ID", kind: .real),
        ]),
        Stream(name: "UserActivityMetadata", title: "User Activity Metadata", fields: [
            Field(path: "2", label: "Activity type"),
            Field(path: "4", label: "Description"),
            Field(path: "5", label: "Bundle ID", kind: .real),
        ]),
        Stream(name: "Wallet.Transaction", title: "Wallet Transactions", fields: [
            Field(path: "1", label: "Pass ID"),
            Field(path: "2", label: "Card Name"),
            Field(path: "3", label: "Field3"),
            Field(path: "4", label: "Transaction UUID"),
            Field(path: "5", label: "Field5"),
        ]),
        Stream(name: "_DKEvent.App.InFocus", title: "In Focus DKEvent", fields: [
            Field(path: "1.1", label: "Activity"),
            Field(path: "2", label: "Time Start", kind: .appleTime),
            Field(path: "3", label: "Time End", kind: .appleTime),
            Field(path: "4.3", label: "Bundle ID"),
            Field(path: "5", label: "Action GUID", kind: .text),
            Field(path: "7", label: "Transition"),
            Field(path: "7.2.3", label: "Transition"),
            Field(path: "8", label: "Time Write", kind: .appleTime),
        ]),
        Stream(name: "_DKEvent.App.Install", title: "App Install", fields: [
            Field(path: "1.1", label: "Activity"),
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "3", label: "Time End", kind: .appleTime),
            Field(path: "4.3", label: "Bundle ID"),
            Field(path: "5", label: "Action GUID", kind: .text),
            Field(path: "7", label: "Bundle Info"),
            Field(path: "8", label: "Time Write", kind: .appleTime),
        ]),
        Stream(name: "_DKEvent.App.LocationActivity", title: "Location Activity", fields: [
            Field(path: "1.1", label: "Activity"),
            Field(path: "2", label: "Time Start", kind: .appleTime),
            Field(path: "3", label: "Time End", kind: .appleTime),
            Field(path: "4.3", label: "Bundle ID"),
            Field(path: "5", label: "Action GUID", kind: .text),
            Field(path: "6.1", label: "Data 0"),
            Field(path: "6.2", label: "Bundle ID 2"),
            Field(path: "7", label: "Data1"),
            Field(path: "8", label: "Time Write", kind: .appleTime),
        ]),
        Stream(name: "_DKEvent.Audio.InputRoute", title: "Audio Input Route DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Start Timestamp", kind: .appleTime),
            Field(path: "3", label: "End Timestamp", kind: .appleTime),
            Field(path: "4.4", label: "Audio Input Route DKEvent"),
            Field(path: "5", label: "GUID"),
            Field(path: "10", label: "Device UTC Offset"),
        ]),
        Stream(name: "_DKEvent.Audio.OutputRoute", title: "Audio Output Route DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Start Timestamp", kind: .appleTime),
            Field(path: "3", label: "End Timestamp", kind: .appleTime),
            Field(path: "4.4", label: "Audio Output Route DKEvent"),
            Field(path: "5", label: "GUID"),
            Field(path: "10", label: "Device UTC Offset"),
        ]),
        Stream(name: "_DKEvent.Carplay.IsConnected", title: "Carplay", fields: [
            Field(path: "1.1", label: "Activity"),
            Field(path: "2", label: "Time Start", kind: .appleTime),
            Field(path: "3", label: "Time End", kind: .appleTime),
            Field(path: "4.4", label: "Carplay"),
            Field(path: "5", label: "Action GUID", kind: .text),
            Field(path: "8", label: "Time Write", kind: .appleTime),
        ]),
        Stream(name: "_DKEvent.Clock.Alarm", title: "Clock Alarm DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Start Timestamp", kind: .appleTime),
            Field(path: "3", label: "End Timestamp", kind: .appleTime),
            Field(path: "4.4", label: "Clock Alarm DKEvent"),
            Field(path: "5", label: "GUID"),
            Field(path: "10", label: "Device UTC Offset"),
        ]),
        Stream(name: "_DKEvent.Device.BatteryPercentage", title: "Battery Percentage", fields: [
            Field(path: "1.1", label: "Activity"),
            Field(path: "2", label: "Time Start", kind: .appleTime),
            Field(path: "3", label: "Time End", kind: .appleTime),
            Field(path: "4.5", label: "Battery Percentage"),
            Field(path: "5", label: "Action GUID", kind: .real),
            Field(path: "8", label: "Time Write", kind: .appleTime),
        ]),
        Stream(name: "_DKEvent.Device.IsLockedImputed", title: "Screen Lock Imputed DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Start Timestamp", kind: .appleTime),
            Field(path: "3", label: "End Timestamp", kind: .appleTime),
            Field(path: "4.4", label: "Screen Lock Imputed DKEvent", values: [0: "Unlocked", 1: "Locked"]),
            Field(path: "5", label: "GUID"),
            Field(path: "10", label: "Device UTC Offset"),
        ]),
        Stream(name: "_DKEvent.Device.IsPluggedIn", title: "Device Plugged In", fields: [
            Field(path: "1.1", label: "Activity"),
            Field(path: "2", label: "Time Start", kind: .appleTime),
            Field(path: "3", label: "Time End", kind: .appleTime),
            Field(path: "4.4", label: "Device Plugged In"),
            Field(path: "5", label: "Action GUID", kind: .text),
            Field(path: "8", label: "Time Write", kind: .appleTime),
        ]),
        Stream(name: "_DKEvent.Device.LowPowerMode", title: "Low Power Mode DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Start Timestamp", kind: .appleTime),
            Field(path: "3", label: "End Timestamp", kind: .appleTime),
            Field(path: "4.4", label: "Low Power Mode DKEvent", values: [0: "Off", 1: "On"]),
            Field(path: "5", label: "GUID"),
            Field(path: "10", label: "Device UTC Offset"),
        ]),
        Stream(name: "_DKEvent.Display.Orientation", title: "Display Orientation DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Start Timestamp", kind: .appleTime),
            Field(path: "3", label: "End Timestamp", kind: .appleTime),
            Field(path: "4.4", label: "Display Orientation DKEvent", values: [0: "Unknown", 1: "Portrait", 2: "Portrait Upside Down", 3: "Landscape Left", 4: "Landscape Right", 5: "Face Up", 6: "Face Down"]),
            Field(path: "5", label: "GUID"),
            Field(path: "10", label: "Device UTC Offset"),
        ]),
        Stream(name: "_DKEvent.Keybag.IsLocked", title: "Keybag", fields: [
            Field(path: "2", label: "Start Time", kind: .appleTime),
            Field(path: "3", label: "End Time", kind: .appleTime),
            Field(path: "4.4", label: "isLocked"),
        ]),
        Stream(name: "_DKEvent.Safari.History", title: "Safari", fields: [
            Field(path: "1.1", label: "Activity"),
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "4.3", label: "URL"),
            Field(path: "5", label: "GUID", kind: .text),
            Field(path: "6.1", label: "Detail"),
            Field(path: "6.2", label: "Detail 2"),
            Field(path: "6.4", label: "Detail 3"),
            Field(path: "7.2.3", label: "Title"),
        ]),
        Stream(name: "_DKEvent.Settings.DoNotDisturb", title: "Do Not Disturb DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Start Timestamp", kind: .appleTime),
            Field(path: "3", label: "End Timestamp", kind: .appleTime),
            Field(path: "4.4", label: "Do Not Disturb DKEvent", values: [0: "Off", 1: "On"]),
            Field(path: "5", label: "GUID"),
            Field(path: "10", label: "Device UTC Offset"),
        ]),
        Stream(name: "_DKEvent.Siri.Ui", title: "Siri UI DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Start Timestamp", kind: .appleTime),
            Field(path: "3", label: "End Timestamp", kind: .appleTime),
            Field(path: "4.4", label: "Siri UI DKEvent"),
            Field(path: "5", label: "GUID"),
            Field(path: "10", label: "Device UTC Offset"),
        ]),
        Stream(name: "_DKEvent.System.AirplaneMode", title: "Airplane Mode DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "3", label: "Timestamp2", kind: .appleTime),
            Field(path: "5", label: "GUID", kind: .bytes),
        ]),
        Stream(name: "_DKEvent.Wifi.Connection", title: "WiFi DKEvent", fields: [
            Field(path: "1.1", label: "Event"),
            Field(path: "2", label: "Timestamp", kind: .appleTime),
            Field(path: "4.3", label: "Device"),
            Field(path: "5", label: "GUID", kind: .bytes),
        ]),
    ]
}
